# Generated by Django 5.2.7 on 2026-04-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MS', '0003_alter_feedback_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
