# Generated by Django 5.2.7 on 2026-04-13 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MS', '0004_clinic_latitude_clinic_longitude_alter_clinic_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='clinic_name',
        ),
        migrations.AddField(
            model_name='clinic',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='MS.clinic'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='available',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
