# Generated by Django 5.2.7 on 2026-04-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MS', '0005_remove_doctor_clinic_name_clinic_user_doctor_clinic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='clinic',
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
