# Generated by Django 5.2.7 on 2026-04-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MS', '0008_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
